# Generated by Django 5.1.5 on 2025-02-25 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('artist', models.CharField(max_length=255)),
                ('image_url', models.URLField()),
                ('key', models.CharField(blank=True, max_length=10, null=True)),
                ('tempo', models.CharField(blank=True, max_length=10, null=True)),
                ('time_signature', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
