# Generated by Django 5.1.5 on 2025-02-25 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='chords',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
