# Generated by Django 5.1.5 on 2025-02-25 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_song_chords'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='timeSignature',
            new_name='time_signature',
        ),
        migrations.RemoveField(
            model_name='song',
            name='chords',
        ),
        migrations.RemoveField(
            model_name='song',
            name='guitar_tabs_url',
        ),
        migrations.RemoveField(
            model_name='song',
            name='sheet_music_url',
        ),
        migrations.AlterField(
            model_name='song',
            name='lyrics',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
