# Generated by Django 5.1.5 on 2025-02-25 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_time_signature_song_timesignature_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='guitar_tabs_url',
        ),
        migrations.RemoveField(
            model_name='song',
            name='sheet_music_url',
        ),
        migrations.AddField(
            model_name='song',
            name='original_song',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='api.song'),
        ),
        migrations.AddField(
            model_name='song',
            name='version',
            field=models.IntegerField(default=1),
        ),
    ]
