# Generated by Django 5.1.6 on 2025-02-25 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_versio_song_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='original_song',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versions', to='api.song'),
        ),
    ]
