# Generated by Django 5.1.6 on 2025-03-06 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_song_original_song'),
        ('guitartabs', '0003_guitartab_key_guitartab_tempo'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='bold_lyrics',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='guitar_tab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='songs', to='guitartabs.guitartab'),
        ),
    ]
