# Generated by Django 5.1.6 on 2025-03-06 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_song_bold_lyrics_song_guitar_tab'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='bold_lyrics',
        ),
    ]
