# Generated by Django 5.1.5 on 2025-02-25 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('songs', '0002_delete_song'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('artist', models.CharField(max_length=200)),
                ('imageUrl', models.URLField(blank=True, null=True)),
                ('key', models.CharField(blank=True, max_length=10, null=True)),
                ('tempo', models.CharField(blank=True, max_length=20, null=True)),
                ('timeSignature', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lyrics', models.TextField(blank=True, null=True)),
                ('chords', models.TextField(blank=True, null=True)),
                ('sheet_music_url', models.URLField(blank=True, null=True)),
                ('guitar_tabs_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
