# Generated by Django 5.1.5 on 2025-02-25 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0005_rename_timesignature_song_time_signature_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='time_signature',
            new_name='timeSignature',
        ),
        migrations.AddField(
            model_name='song',
            name='guitar_tabs_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='sheet_music_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
