# Generated by Django 5.1.5 on 2025-02-25 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0007_remove_song_guitar_tabs_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='version',
        ),
        migrations.AddField(
            model_name='song',
            name='versio',
            field=models.IntegerField(default=1),
        ),
    ]
