# Generated by Django 5.1.5 on 2025-02-25 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0008_remove_song_version_song_versio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='versio',
            new_name='version',
        ),
    ]
