# Generated by Django 5.2.5 on 2025-11-06 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0013_songflow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='timeSignature',
            new_name='time_signature',
        ),
    ]
