# Generated by Django 5.1.5 on 2025-02-27 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guitartabs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guitartab',
            name='original_tab',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versions', to='guitartabs.guitartab'),
        ),
        migrations.AddField(
            model_name='guitartab',
            name='version',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='guitartab',
            name='tab_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
