# Generated by Django 5.1.5 on 2025-02-27 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guitartabs', '0002_guitartab_original_tab_guitartab_version_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guitartab',
            name='key',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='guitartab',
            name='tempo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
